### ISSUE TITLE
How to run project

### ISSUE THREAD

**Issue by morenoh149** [mdn/django-diy-blog#1]
I'd like to run this software. How do I do so?
I see no virtualenv nor any requirements.txt file.

**Comment by chrisdavidmills** [comment]
Hi there,

This repo contains the solution for the assessment at the end of this tutorial series:

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django

You can run it by using instructions similar to this:

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/development_environment

In the end we didn't use virtualenv to make it simpler for complete beginners to understand.

**Comment by morenoh149** [comment]
could you reconsider in light of https://docs.pipenv.org/ gaining recommendation from the PSF?

**Comment by bsmth** [comment]
Closing this one as it looks like it's fixed in https://github.com/mdn/django-diy-blog/commit/dab0dfc81b7758b2902eedf804ee49a11cdbfad5
