### ISSUE TITLE
Why Foreign Key in user in BlogAuthor?

### ISSUE THREAD

**Issue by SubhankarHalder** [mdn/django-diy-blog#10]
Hello! I am new to Django and I am trying to finish the Django assessment. In file blog/models.py line 15, the code is:

user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

for the class BlogAuthor.

However, I believe the relationship should be OneToOneField. Only one User should map to one BlogAuthor and this should be true for the converse relation. One User cannot be many BlogAuthors. Right?

**Comment by hamishwillee** [comment]
You are correct. Well done - you pass :-) 

Feel free to create and test a PR to fix this.
