### ISSUE TITLE
Making comments without being a an authenticated user. 

### ISSUE THREAD

**Issue by Kelvxn** [mdn/django-diy-blog#17]
The BlogComment model class being related to "User" means that only authenticated users can comment to a blog right??

**Comment by hamishwillee** [comment]
The bit that makes login required is here: https://github.com/mdn/django-diy-blog/blob/master/blog/views.py#L81

```
class BlogCommentCreate(LoginRequiredMixin, CreateView):
    """
    Form for adding a blog comment. Requires login. 
    """
```
